### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lentou** [MCPE-PC/OreAboveEndStone#3]
When you break an ore below on end , it stops the server

**Comment by MCPE-PC** [comment]
? What did you mean?
무슨 말입니까?

**Comment by lentou** [comment]
I place End stone , then the ore is popup and I break it so after a while the server will stop

**Comment by MCPE-PC** [comment]
Um okay

**Comment by MCPE-PC** [comment]
What is your PM API version? And did you ever modify ore.json?

**Comment by lentou** [comment]
3.0.0-ALPHA11 , I dont modify ore.json

**Comment by MCPE-PC** [comment]
Please give me its crashdump if it was crashed.

**Comment by MCPE-PC** [comment]
@Hytlenz

**Comment by lentou** [comment]
There's no crashdump, if you break so many times the ore above end stone, It stops the server

**Comment by MCPE-PC** [comment]
Okay @Hytlenz , I will test it.

**Comment by MCPE-PC** [comment]
It makes lag sometimes and sometimes ores become transparent, but it didn't make server stop.
Please let me know your computer's specifications.

**Comment by MCPE-PC** [comment]
@Hytlenz Hey, please tell me how to reproduce it.
